### ISSUE TITLE
詢問docker_test.sh未通過原因

### ISSUE THREAD

**Issue by gigi-igig** [NYCU-SDC/backend-training-2024#14]
您好，

因為在 Windows PowerShell 中執行指令時，
執行 git remote add origin https://github.... 的過程中，
出現了以下警告：
warning: in the working copy of '.gitmodules', LF will be replaced by CRLF the next time Git touches it

想詢問是否因為LF和CRLF的轉換導致docker_test.sh無法通過?
未通過的部分: OCI runtime exec failed: exec failed: Cwd must be an absolute path: unknown

謝謝!

**Comment by kdotwei** [comment]
同學你好，

再麻煩你將錯誤訊息及前後執行的指令都一起截圖上來
方便我們了解更多 detail 來幫助你
謝謝！

**Comment by gigi-igig** [comment]
您好，
以下是我的螢幕錄影，
[螢幕錄影.zip](https://github.com/user-attachments/files/17100602/default.zip)
謝謝!

**Comment by linoil** [comment]
@gigi-igig  
關於 `OCI runtime exec failed: exec failed: Cwd must be an absolute path: unknown` 這個問題可能是你執行 script 的時候是使用 Git Bash 導致的。
如果是使用 WSL 去跑 `docker_test.sh` 的話就可以順利執行。

執行之前，要記得確定 WSL 和 Docker Desktop 上的設定有沒有設好，可以參考 [這個文件](https://learn.microsoft.com/zh-tw/windows/wsl/tutorials/wsl-containers)。

`warning: in the working copy of '.gitmodules', LF will be replaced by CRLF the next time Git touches it` 這個問題的話是因為換行的方式在不同的作業系統有不同處理方式，單純提示你說它會自動幫你做轉換。可以下指令設定，網路上蠻多方法可以去參考看看。

有其他任何問題可以再提問！

**Comment by gigi-igig** [comment]
解決方式
透過:
git status
先確認有沒有因權限更改的改變，如果有再執行
git restore .
