### ISSUE TITLE
詢問The requested URL returned error: 403的原因與解決辦法

### ISSUE THREAD

**Issue by Hank-Chang407** [NYCU-SDC/backend-training-2024#21]
git push後 ，terminal上顯示：
remote: Permission to NYCU-SDC/backend-training-2024.git denied to Hank-Chang407.
fatal: unable to access 'https://github.com/NYCU-SDC/backend-training-2024.git/': The requested URL returned error: 403
網路上的資源提出使用SSH key等相關辦法，不過我嘗試了許久，發現可能是Permission to NYCU-SDC/backend-training-2024.git的問題，也有可能是因為我對SSH key的用法不是很熟悉，導致未能解決問題。希望在這裡疑問可以得到解決，謝謝您的瀏覽 
<img width="1440" alt="截圖 2024-09-21 晚上10 28 15" src="https://github.com/user-attachments/assets/fcd7dfe0-b6a7-458a-9b38-64b0a339776c">

**Comment by kdotwei** [comment]
同學你好，

你有先將原本的 Repo Fork 出來到自己的帳號中嗎？
此情況有可能是因為你直接推到 NYCU-SDC/backend-training-2024 而非 <your-github-id>/backend-training-2024。
