### ISSUE TITLE
您好,想請問Window使用者如何運行docker_test.sh

### ISSUE THREAD

**Issue by MING-CHUNLee** [NYCU-SDC/backend-training-2024#53]
您好！我嘗試使用Git bash來運行docker_test.sh,但遇到**OCI runtime exec failed: exec failed: Cwd must be an absolute path: unknown**，請問該如何解決或是否能提供相關的參考資源，謝謝您

系統運行過程如下:
```
Mindy@LAPTOP-O299TGTI MINGW64 ~/CODE/Python/SDC/backend-training-2024 (main)
$ ./docker_test.sh
============================== Check files change ==============================
Modified files:
.gitmodules
members/Lyc1103
Only members/ directory or .gitmodules was modified. Proceeding...
============================= Install requirements =============================
OCI runtime exec failed: exec failed: Cwd must be an absolute path: unknown
================================== Run pytest ==================================
OCI runtime exec failed: exec failed: Cwd must be an absolute path: unknown
OCI runtime exec failed: exec failed: Cwd must be an absolute path: unknown
OCI runtime exec failed: exec failed: Cwd must be an absolute path: unknown

```

**Comment by kd229y** [comment]
開wsl跑

**Comment by MING-CHUNLee** [comment]
> 開wsl跑
請請問您的意思是打開這個WSL進入的CMD視窗嗎?但我點擊時會閃退。請問您有遇過這樣的問題嗎?
![image](https://github.com/user-attachments/assets/152a59fc-cd0d-4b7b-9f0d-a882b5b77856)

**Comment by kd229y** [comment]
我是在vscode裡面跑的，你可以試試看，我是沒有閃退過

**Comment by gigi-igig** [comment]
可以嘗試直接在windows powershell裡面，直接輸入:
wsl
就會切換成wsl。
如果出現bad interpreter: No such file or directory的話，可以再輸入:
dos2unix ./docker_test.sh
就可以執行docker_test.sh了(再輸入一次: ./docker_test.sh)

**Comment by MING-CHUNLee** [comment]
> 可以嘗試直接在windows powershell裡面，直接輸入: wsl 就會切換成wsl。 如果出現bad interpreter: No such file or directory的話，可以再輸入: dos2unix ./docker_test.sh 就可以執行docker_test.sh了(再輸入一次: ./docker_test.sh)

謝謝您詳細的教學！但當我嘗試切換WSL,出現ERROR: CreateProcessParseCommon:711: Failed to translate 
依照ChatGPT的指示確實Docker 為wsl 2，也嘗試過wsl --update
因為還有其他專案跑在Ubuntu所以沒辦法重新卸載
![image](https://github.com/user-attachments/assets/0a961197-18bb-4c8b-a22a-23ce077a3df1)
![image](https://github.com/user-attachments/assets/83f02a33-c3a1-49cf-a069-5d6d782cc6cd)

**Comment by MING-CHUNLee** [comment]
> 我是在vscode裡面跑的，你可以試試看，我是沒有閃退過

了解!謝謝您!

**Comment by MING-CHUNLee** [comment]
感謝老師們和大家的幫忙已解決！
