### ISSUE TITLE
請問 pull request

### ISSUE THREAD

**Issue by vch2128** [NYCU-SDC/backend-training-2024#56]
Hosts們好：

想請問我的 pull request 發出後，為什麼沒有出現在 members 的資料夾裡面呢？
在我自己 fork 出去的 repository 裡面的 members 資料夾已經有出現我自己帳號的資料夾，但在 SDC 的 repository 就沒有。
想請問 hosts 是否有哪個步驟我做錯了，謝謝！

**Comment by vch2128** [comment]
另外想請問在執行 ./docker_test.sh 時，出現這個錯誤應該要怎麼解決呢？
![image](https://github.com/user-attachments/assets/b20fce25-4f77-4bb5-b91f-26887bab72e0)

錯誤訊息中說 “remove __pycache__ / .pyc files and/or use a unique basename for your test file modules” ，但在檢查之後我已經刪除資料夾中的其他 __pycache__ / .pyc 檔案，也沒有找到相同名稱的其他檔案
訊息中說的 “/mnt/test/test_hello_world.py” 也不存在這個路徑

**Comment by vch2128** [comment]
另外想請問，我新發的 pull request 中有一個 checkpoint 沒有通過，是說我有 file modification（刪除之前的兩個.example檔）
請問這樣是可以的嗎？謝謝 hosts！

**Comment by as535364** [comment]
1. pull request 發出後要被 host merge 進來才會看到資料夾出現在 SDC 的 repository 裡面
2. 這樣是不行的，請把 SDC 原有的檔案放回去，不然會過不了檢查 （所有的更動只在你自己的 fastapi repo，發 PR 用的 repo 只用來新增 / 更新 submodule 用）

**Comment by vch2128** [comment]
好的，謝謝 host！
