### ISSUE TITLE
在local端跑docker_test.sh跑不過

### ISSUE THREAD

**Issue by Dart147** [NYCU-SDC/backend-training-2024#61]
檔案檢查有過，但跑後面的script就報錯了，如下截圖
<img width="949" alt="Screenshot 2024-09-29 at 9 50 22 PM" src="https://github.com/user-attachments/assets/9969262b-b39c-478b-890d-33d6515d5d98">
<img width="1488" alt="Screenshot 2024-09-29 at 9 48 22 PM" src="https://github.com/user-attachments/assets/07067b7a-d288-4dbf-a99e-78a7f9dd5ab2">
想請問可能是遇到什麼問題？謝謝

**Comment by kdotwei** [comment]
已於 Office Hour 解決。
